apiVersion: "spark-operator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-app-example
  namespace: default
spec:
  type: Scala
  mode: cluster
  mainApplicationFile: "local:///opt/spark/examples/jars/spark_examples_2.11-2.2.0.jar"
  driver:
    driverSecrets:
    - name: spark-secret
      path: "/opt/spark/secrets"
      type: GCPServiceAccount
    driverEnvVars:
      "GOOGLE_APPLICATION_CREDENTIALS": "/opt/spark/secrets/key.json"
  executor:
    executorSecrets:
    - name: spark-secret
      path: "/opt/spark/secrets"
      type: GCPServiceAccount
    executorEnvVars:
      "GOOGLE_APPLICATION_CREDENTIALS": "/opt/spark/secrets/key.json"
  submissionByUser: true
