apiVersion: "spark-operator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-app-example
  namespace: default
spec:
  type: Scala
  mode: cluster
  mainApplicationFile: "local:///opt/spark/examples/jars/spark_examples_2.11-2.2.0.jar"
  driver:
    image: "kubespark/spark-driver:v2.1.0-kubernetes-0.3.1"
  executor:
    image: "kubespark/spark-executor:v2.1.0-kubernetes-0.3.1"
    instances: 1
  submissionByUser: true
