apiVersion: "spark-operator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-app-example
  namespace: default
spec:
  type: Scala
  mode: cluster
  mainApplicationFile: "local:///opt/spark/examples/jars/spark_examples_2.11-2.2.0.jar"
  driver:
    image: "liyinan926/spark-driver:latest"
  executor:
    image: "liyinan926/spark-executor:latest"
    instances: 1
  submissionByUser: false
