apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark-operator
  namespace: default
  labels:
    app: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-operator
  template:
    metadata:
      labels:
        app: spark-operator
      initializers:
        pending: []  
    spec:
      containers:
      - name: spark-operator
        image: liyinan926/spark-operator:latest
        imagePullPolicy: Always
        command: ["/usr/bin/spark-operator"]
        args:
        - --logtostderr